---
sidebar: sidebar
permalink: reference-new.html
keywords: what's new, new, features, release notes, enhancements
summary: Cloud Volumes ONTAP 9.9.0 includes several new features and enhancements.
---

= What's new in Cloud Volumes ONTAP 9.9.0
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP 9.9.0 includes several new features and enhancements.

Additional features and enhancements are also introduced in the latest versions of BlueXP. See the https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html[BlueXP Release Notes^] for details.

== c4, m4, and r4 instances no longer supported (28 October 2022)

In AWS, the c4, m4, and r4 EC2 instance types are no longer supported with Cloud Volumes ONTAP. If you have an existing system that’s running on a c4, m4, or r4 instance type, you must change to an instance type in the c5, m5, or r5 instance family.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html[Learn how to change the EC2 instance type for Cloud Volumes ONTAP^].

Refer to link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html[NetApp Support^] to learn more about the end of availability and support for these instance types. 

== Latest update (21 Apr 2021)

In AWS, you can now configure up to 24 storage VMs (SVMs) for disaster recovery (DR). The previous limit was 12 storage VMs used for DR.

link:reference-limits-aws.html#storage-vm-limits[Learn more about storage VM limits].

== Latest updates (12 Apr 2021)

A few updates have been made since Cloud Volumes ONTAP 9.9.0 was released.

*AWS updates*

* Cloud Volumes ONTAP now supports General Purpose SSD (gp3) disks, starting with the 9.7 release. gp3 disks are the lowest-cost SSDs that balance cost and performance for a broad range of workloads.
+
https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-planning-your-config.html#sizing-your-system-in-aws[Learn more about using gp3 disks with Cloud Volumes ONTAP^].

* Cloud Volumes ONTAP no longer supports Cold HDD (sc1) disks.

These EBS disk changes were introduced as part of BlueXP 3.9.5.

*Azure updates*

* New E series VM types are supported:

** E4s_v3 with single node systems using PAYGO Explore or BYOL
** E8s_v3 with single node systems using PAYGO Standard or BYOL, and HA pairs using PAYGO Premium or BYOL
** E64is_v3 with single node systems using PAYGO Premium or BYOL

* Up to 24 storage VMs (SVMs) are supported with Cloud Volumes ONTAP BYOL. Those 24 storage VMs can serve data or be configured for disaster recovery (DR).
+
The previous limit in the 9.9.0 release was 12 storage VMs used for DR in Azure.

== 9.9.0 GA (9 Mar 2021)

The 9.9.0 GA release is available in AWS, Azure, and Google Cloud Platform. The release includes the following new features and enhancements.

=== Improved write performance

This release includes improved write performance for Cloud Volumes ONTAP in all cloud providers and on all configurations.

=== Support for new EC2 instance types

Cloud Volumes ONTAP is now supported with the following Amazon EC2 instance types:

* m5a.2xlarge with Standard and BYOL
* m5a.16xlarge with Premium and BYOL
* c5a.12xlarge with Premium and BYOL

Learn more about https://aws.amazon.com/ec2/instance-types/m5/[M5a instances^] and https://aws.amazon.com/ec2/instance-types/c5/[C5a instances^].

link:reference-configs-aws.html[View supported configurations in AWS].

=== Support for 24 storage VMs in Azure

24 storage VMs are now supported with Cloud Volumes ONTAP in Azure when you bring your own license (BYOL). This includes up to 12 storage VMs used for DR.

An add-on license is required for each additional _data-serving_ storage VM beyond the first storage VM that comes with Cloud Volumes ONTAP by default. Contact your account team to obtain an SVM add-on license.

Storage VMs that you configure for disaster recovery (DR) don't require an add-on license (they are free of charge), but they do count against the storage VM limit.

link:reference-limits-azure.html#storage-vm-limits[Learn more about storage VM limits in Azure].

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-azure.html[Learn how to create data-serving storage VMs for Cloud Volumes ONTAP in Azure^].

== Required version of the BlueXP Connector

The BlueXP Connector must be running version 3.9.4 or later to deploy new Cloud Volumes ONTAP 9.9.0 systems and to upgrade existing systems to 9.9.0.

== Changes introduced with version 3.9.4 of the Connector

The 3.9.4 release of the Connector includes a few enhancements for the management of Cloud Volumes ONTAP, including enhancements to AWS KMS support, shared VPC support in Google Cloud, and reduced IPs in Google Cloud.

Go to the https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html[BlueXP Release Notes^] for more details about the 3.9.4 release.

== Upgrade notes

* Upgrades of Cloud Volumes ONTAP must be completed from BlueXP. You should not upgrade Cloud Volumes ONTAP by using System Manager or the CLI. Doing so can impact system stability.

* You can upgrade to Cloud Volumes ONTAP 9.9.0 from the 9.8 release. BlueXP will prompt you to upgrade your existing Cloud Volumes ONTAP 9.8 systems to the 9.9.0 release.
+
http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html[Learn how to upgrade when BlueXP notifies you^].

* The upgrade of a single node system takes the system offline for up to 25 minutes, during which I/O is interrupted.

* Upgrading an HA pair is nondisruptive and I/O is uninterrupted. During this nondisruptive upgrade process, each node is upgraded in tandem to continue serving I/O to clients.
